/* ═══════════════════════════════════════════
   Catálogo quemado — fuente única de datos
   ═══════════════════════════════════════════ */

export const CATEGORIES = [
  { id: 'all',         label: 'Todo',        icon: 'sparkles' },
  { id: 'laptops',     label: 'Laptops',     icon: 'laptop' },
  { id: 'audio',       label: 'Audio',       icon: 'headphones' },
  { id: 'phones',      label: 'Smartphones', icon: 'smartphone' },
  { id: 'wearables',   label: 'Wearables',   icon: 'watch' },
  { id: 'gaming',      label: 'Gaming',      icon: 'gamepad-2' },
  { id: 'accessories', label: 'Accesorios',  icon: 'mouse' },
];

export const SORT_OPTIONS = [
  { id: 'relevance',  label: 'Relevancia' },
  { id: 'price-asc',  label: 'Precio ↑' },
  { id: 'price-desc', label: 'Precio ↓' },
  { id: 'rating',     label: 'Mejor rating' },
  { id: 'newest',     label: 'Más nuevos' },
];

export const TAGS = [
  { id: 'sale', label: 'En oferta',     icon: 'tag' },
  { id: 'new',  label: 'Nuevos',        icon: 'sparkles' },
  { id: 'hot',  label: 'Más vendidos',  icon: 'flame' },
];

export const PRICE_BUCKETS = [
  { id: 'all',       label: 'Cualquier precio', test: null },
  { id: '0-200',     label: 'Menos de $200',    test: (p) => p < 200 },
  { id: '200-500',   label: '$200 – $500',      test: (p) => p >= 200 && p < 500 },
  { id: '500-1000',  label: '$500 – $1,000',    test: (p) => p >= 500 && p < 1000 },
  { id: '1000+',     label: '$1,000 o más',     test: (p) => p >= 1000 },
];

const img = (id, w = 600) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

export const PRODUCTS = [
  {
    id: 'p01',
    name: 'MacBook Pro 14" M3 Max',
    brand: 'Apple',
    category: 'laptops',
    price: 2499,
    priceOld: 2799,
    rating: 4.9,
    reviews: 1284,
    stock: 12,
    image: img('1517336714731-489689fd1ca8'),
    badges: ['sale', 'hot'],
    featured: true,
    specs: ['Chip M3 Max 16-core', '36GB RAM unificada', 'SSD 1TB NVMe', 'Pantalla Liquid Retina XDR 14.2"', '22h batería'],
    description: 'Rendimiento profesional con el chip M3 Max. Ideal para edición de video 8K, desarrollo y workflows creativos exigentes.',
  },
  {
    id: 'p02',
    name: 'ThinkPad X1 Carbon Gen 12',
    brand: 'Lenovo',
    category: 'laptops',
    price: 1899,
    rating: 4.7,
    reviews: 562,
    stock: 8,
    image: img('1496181133206-80ce9b88a853'),
    badges: ['new'],
    specs: ['Intel Core Ultra 7', '32GB LPDDR5X', 'SSD 1TB', 'Pantalla OLED 2.8K', 'Certificado MIL-STD'],
    description: 'Ultrabook empresarial con durabilidad militar y rendimiento silencioso.',
  },
  {
    id: 'p03',
    name: 'ROG Zephyrus G16',
    brand: 'ASUS',
    category: 'laptops',
    price: 2199,
    priceOld: 2399,
    rating: 4.6,
    reviews: 341,
    stock: 5,
    image: img('1593642632823-8f785ba67e45'),
    badges: ['sale'],
    specs: ['RTX 4080 12GB', 'Intel Core i9-14900H', '32GB DDR5', 'OLED 240Hz', 'Teclado AniMe Matrix'],
    description: 'Laptop gamer con OLED de 240Hz y diseño ultra-delgado.',
  },

  {
    id: 'p04',
    name: 'AirPods Pro 2 (USB-C)',
    brand: 'Apple',
    category: 'audio',
    price: 229,
    priceOld: 249,
    rating: 4.8,
    reviews: 9421,
    stock: 47,
    image: img('1606220588913-b3aacb4d2f46'),
    badges: ['sale'],
    specs: ['Cancelación activa H2', 'Audio espacial personalizado', 'Hasta 6h con ANC', 'Estuche MagSafe USB-C', 'IP54'],
    description: 'ANC líder de la industria en formato in-ear con chip H2.',
  },
  {
    id: 'p05',
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'audio',
    price: 379,
    rating: 4.8,
    reviews: 5217,
    stock: 23,
    image: img('1505740420928-5e560c06d30e'),
    badges: ['hot'],
    specs: ['ANC adaptativo', 'Drivers 30mm', '30h batería', 'LDAC + Hi-Res', 'Multipunto Bluetooth'],
    description: 'Los reyes del silencio. Drivers ultra-ligeros y carga rápida USB-C.',
  },
  {
    id: 'p06',
    name: 'Bose QuietComfort Ultra',
    brand: 'Bose',
    category: 'audio',
    price: 429,
    rating: 4.6,
    reviews: 1024,
    stock: 14,
    image: img('1546435770-a3e426bf472b'),
    badges: ['new'],
    specs: ['Audio Inmersivo', 'ANC CustomTune', '24h batería', 'Snapdragon Sound', 'Multipunto'],
    description: 'Audio inmersivo que transforma cualquier track en 3D.',
  },

  {
    id: 'p07',
    name: 'iPhone 15 Pro Max 256GB',
    brand: 'Apple',
    category: 'phones',
    price: 1199,
    rating: 4.9,
    reviews: 7832,
    stock: 19,
    image: img('1592899677977-9c10ca588bbd'),
    badges: ['hot'],
    specs: ['Chip A17 Pro 3nm', 'Titanio grado 5', 'Cámara 5x tele periscopio', 'Acción personalizable', 'USB-C 3'],
    description: 'El primer iPhone de titanio con zoom óptico 5x.',
  },
  {
    id: 'p08',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'phones',
    price: 1299,
    priceOld: 1399,
    rating: 4.8,
    reviews: 4310,
    stock: 22,
    image: img('1610945265064-0e34e5519bbf'),
    badges: ['sale', 'new'],
    specs: ['Snapdragon 8 Gen 3 for Galaxy', 'Galaxy AI integrada', 'Cámara 200MP', 'S Pen incluido', 'Pantalla 6.8" QHD+ 120Hz'],
    description: 'IA generativa en el bolsillo. Cámara de 200MP y S Pen.',
  },
  {
    id: 'p09',
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    category: 'phones',
    price: 999,
    rating: 4.7,
    reviews: 2018,
    stock: 15,
    image: img('1598327105666-5b89351aff97'),
    badges: [],
    specs: ['Tensor G3', 'Android puro 7 años soporte', 'Cámara computacional', 'Magic Editor', 'Pantalla Super Actua LTPO'],
    description: 'La IA de Google potencia cada foto y cada gesto.',
  },

  {
    id: 'p10',
    name: 'Apple Watch Ultra 2',
    brand: 'Apple',
    category: 'wearables',
    price: 799,
    rating: 4.8,
    reviews: 3122,
    stock: 11,
    image: img('1551816230-ef5deaed4a26'),
    badges: ['new'],
    specs: ['Titanio 49mm', 'Pantalla 3000 nits', 'GPS de doble frecuencia', '36h batería', 'WR100 + EN13319'],
    description: 'El smartwatch más robusto de Apple para aventura y deporte extremo.',
  },
  {
    id: 'p11',
    name: 'Garmin Fenix 7X Solar',
    brand: 'Garmin',
    category: 'wearables',
    price: 899,
    priceOld: 999,
    rating: 4.7,
    reviews: 892,
    stock: 7,
    image: img('1579586337278-3befd40fd17a'),
    badges: ['sale'],
    specs: ['Carga solar Power Glass', 'Mapas topográficos', '37d batería smart', 'Pulse Ox', 'MIL-STD-810'],
    description: 'Autonomía récord con carga solar. Para quien nunca se detiene.',
  },

  {
    id: 'p12',
    name: 'PlayStation 5 Slim',
    brand: 'Sony',
    category: 'gaming',
    price: 499,
    rating: 4.9,
    reviews: 12054,
    stock: 30,
    image: img('1606144042614-b2417e99c4e3'),
    badges: ['hot'],
    specs: ['SSD custom 1TB', 'Ray-tracing HW', '4K 120Hz / 8K', 'DualSense haptic', 'Lector Blu-ray UHD'],
    description: 'Nuevo diseño slim con 1TB. La siguiente generación del gaming.',
  },
  {
    id: 'p13',
    name: 'Xbox Series X',
    brand: 'Microsoft',
    category: 'gaming',
    price: 499,
    rating: 4.8,
    reviews: 8765,
    stock: 18,
    image: img('1621259182978-fbf93132d53d'),
    badges: [],
    specs: ['12 TFLOPS RDNA 2', 'SSD 1TB Velocity', '4K 120fps', 'Quick Resume', 'Dolby Vision / Atmos'],
    description: 'La consola más potente de Microsoft con Game Pass Ultimate.',
  },
  {
    id: 'p14',
    name: 'Meta Quest 3 128GB',
    brand: 'Meta',
    category: 'gaming',
    price: 499,
    priceOld: 549,
    rating: 4.6,
    reviews: 2431,
    stock: 25,
    image: img('1592478411213-6153e4ebc07d'),
    badges: ['sale', 'new'],
    specs: ['Snapdragon XR2 Gen 2', 'Pancake lenses 4K+', 'Mixed Reality a color', 'Touch Plus controllers', '2h batería'],
    description: 'Realidad mixta a color con paso exterior de alta fidelidad.',
  },

  {
    id: 'p15',
    name: 'Logitech MX Master 3S',
    brand: 'Logitech',
    category: 'accessories',
    price: 99,
    priceOld: 119,
    rating: 4.9,
    reviews: 18392,
    stock: 120,
    image: img('1527864550417-7fd91fc51a46'),
    badges: ['sale'],
    specs: ['Sensor 8000 DPI', 'Silent clicks', 'MagSpeed scroll', 'USB-C carga rápida', 'Multi-device Flow'],
    description: 'El mouse favorito de devs y creativos. Preciso, silencioso, multi-OS.',
  },
  {
    id: 'p16',
    name: 'Keychron K2 Pro QMK',
    brand: 'Keychron',
    category: 'accessories',
    price: 139,
    rating: 4.8,
    reviews: 4521,
    stock: 42,
    image: img('1587829741301-dc798b83add3'),
    badges: ['hot'],
    specs: ['Hot-swappable', 'Switches Gateron Pro', 'QMK/VIA open firmware', 'RGB por tecla', 'Bluetooth 5.1 + USB-C'],
    description: 'Teclado mecánico 75% hot-swappable con firmware abierto.',
  },
];

export const getProduct = (id) => PRODUCTS.find(p => p.id === id);
export const getFeatured = () => PRODUCTS.find(p => p.featured) ?? PRODUCTS[0];

export const getBrands = () =>
  [...new Set(PRODUCTS.map(p => p.brand))].sort((a, b) => a.localeCompare(b));
